### PR TITLE
Display the full of error message #608

### PR DESCRIPTION
**Pull request by samaradel**

### CODE REVIEW

**Comment by grimpy** [comment]
Could a add a screenshot before and after?

**Comment by samaradel** [comment]
Before
grid nodestatus-before

After
grid nodestatus

**Comment by grimpy** [comment]
I'm not convinced with this changed cause in some places we have very long messages which will occupy atleast 5lines. What do you think @yveskerwyn?

**Comment by samaradel** [comment]
we can make the text ellipsis like before and display it on hover/click/show more link

**Comment by yveskerwyn** [comment]
@grimpy with the current implementation we have a problem with even the shorter messages, so I'm OK with those very long messages items, in the future we could open a Details page with more details?

**Pull request merged**
